testProgram  = "{\n";
testProgram += "\tint a\n";
testProgram += "\ta = 1\n";
testProgram += "\t{\n";
testProgram += "\t\tint a\n";
testProgram += "\t\ta = 2\n";
testProgram += "\t\tprint(a)\n";
testProgram += "\t}\n";
testProgram += "\tstring b\n";
testProgram += "\tb = \"alan\"\n";
testProgram += "\tif(a == 1) {\n";
testProgram += "\t\tprint(b)\n";
testProgram += "\t}\n";
testProgram += "\tstring c\n";
testProgram += "\tc = \"james\"\n";
testProgram += "\tb = \"blackstone\"\n";
testProgram += "\tprint(b)\n";
testProgram += "} $";

testProgram  = "{\n";
testProgram += "\tint a\n";
testProgram += "\tint b\n";
testProgram += "\tint c\n";
testProgram += "\ta = 1\n";
testProgram += "\tb = 1\n";
testProgram += "\tc = 1\n";
testProgram += "\twhile(a == 1) {\n";
testProgram += "\t\tprint(\"loop \")\n";
testProgram += "\t\tprint(b)\n";
testProgram += "\t\tif(c == 2) {\n";
testProgram += "\t\t\ta = 2\n";
testProgram += "\t\t}\n";
testProgram += "\t\tif(b == 2) {\n";
testProgram += "\t\t\tb = 3\n";
testProgram += "\t\t\tc = 2\n";
testProgram += "\t\t}\n";
testProgram += "\t\tif(b == 1) {\n";
testProgram += "\t\t\tb = 2\n";
testProgram += "\t\t}\n";
testProgram += "\t}\n";
testProgram += "} $";

testProgram  = "{\n";
testProgram += "\tint a\n";
testProgram += "\t{\n";
testProgram += "\t\tint a\n";
testProgram += "\t\ta = 3\n";
testProgram += "\t\tprint(a)\n";
testProgram += "\t}\n";
testProgram += "\t{\n";
testProgram += "\t\tint a\n";
testProgram += "\t\ta = 4\n";
testProgram += "\t\tprint(a)\n";
testProgram += "\t}\n";
testProgram += "\t{\n";
testProgram += "\t\ta = 5\n";
testProgram += "\t}\n";
testProgram += "\tprint(a)\n";
testProgram += "} $";

testProgram  = "{\n";
testProgram += "\tint a\n";
testProgram += "\t{\n";
testProgram += "\t\ta = 2\n";
testProgram += "\t\tint a\n";
testProgram += "\t\t{\n";
testProgram += "\t\t\tstring c\n";
testProgram += "\t\t\t{\n";
testProgram += "\t\t\t\ta = 5\n";
testProgram += "\t\t\t\tc = \"hello\"\n";
testProgram += "\t\t\t}\n";
testProgram += "\t\t\tprint(c)\n";
testProgram += "\t\t}\n";
testProgram += "\t\tprint(a)\n";
testProgram += "\t}\n";
testProgram += "\tprint(a)\n";
testProgram += "} $";

testProgram  = "{\n";
testProgram += "\tint a\n";
testProgram += "\ta = 3\n";
testProgram += "\ta = 1 + 2 + a\n";
testProgram += "\tprint(a)\n";
testProgram += "} $";

testProgram  = "{\n";
testProgram += "\tboolean a\n";
testProgram += "\ta = (1 == 2)\n";
testProgram += "\tboolean b\n";
testProgram += "\tb = false\n";
testProgram += "\tif(a == b) {\n";
testProgram += "\t\tprint(\"meow\")\n";
testProgram += "\t}\n";
testProgram += "} $";

testProgram  = "{\n";
testProgram += "\tboolean a\n";
testProgram += "\ta = (true == (2 == 2))\n";
testProgram += "\tif(a == true) {\n";
testProgram += "\t\tprint(\"yay\")\n";
testProgram += "\t}\n";
testProgram += "\t{\n";
testProgram += "\t\tint x\n";
testProgram += "\t\tint y\n";
testProgram += "\t\tx = 5\n";
testProgram += "\t\ty = 6\n";
testProgram += "\t\tif((x == y) == false) {\n";
testProgram += "\t\t\tprint(\"hooray\")\n";
testProgram += "\t\t}\n";
testProgram += "\t}\n";
testProgram += "} $";

testProgram  = "{\n";
testProgram += "\tint i\n";
testProgram += "\ti = 1\n";
testProgram += "\twhile((i == 8) == false) {\n";
testProgram += "\t\tif(i == 1) {\n";
testProgram += "\t\t\tprint(\"begin \")\n";
testProgram += "\t\t}\n";
testProgram += "\t\tprint(\"loop \")\n";
testProgram += "\t\tprint(i)\n";
testProgram += "\t\tprint(" ")\n";
testProgram += "\t\ti = 1 + i\n";
testProgram += "\t}\n";
testProgram += "} $";